# Generated by Django 2.1.5 on 2019-02-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='category',
            new_name='product',
        ),
    ]
