# Generated by Django 2.1.5 on 2019-02-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20190209_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price']},
        ),
    ]
